/*
===============================================================================
DATA SEGMENTATION ANALYSIS
===============================================================================
PURPOSE:
    - TO GROUP DATA INTO MEANINGFUL CATEGORIES FOR TARGETED INSIGHTS.
    - FOR CUSTOMER SEGMENTATION, PRODUCT CATEGORIZATION, OR REGIONAL ANALYSIS.
    
SQL FUNCTIONS USED:
    - CASE: DEFINES CUSTOM SEGMENTATION LOGIC.
    - GROUP BY: GROUPS DATA INTO SEGMENTS.
===============================================================================
*/

-- SEGMENT PRODUCTS INTO COST RANGE AND COUNT HOW MANY PRODUCTS FALL INTO EACH SEGMENT.
WITH PRODUCT_SEGMENT AS(
SELECT 
	PRODUCT_KEY,
    PRODUCT_NAME,
    COST,
    CASE
		WHEN COST < 100 THEN 'BELOW 100'
        WHEN COST BETWEEN 100 AND 500 THEN '100 - 500'
        WHEN COST BETWEEN 500 AND 1000 THEN '500-1000'
        ELSE 'ABOVE 1000'
	END COST_RANGE
FROM GOLD_DIM_PRODUCTS)
SELECT 
COST_RANGE,
COUNT(PRODUCT_KEY) AS TOTAL_PRODUCTS
FROM PRODUCT_SEGMENT GROUP BY COST_RANGE
ORDER BY TOTAL_PRODUCTS DESC;

/* GROUP CUSTOMERS INTO THREE SEGMENTS BASED ON THEIR SPENDING BEHAVIOUR
-- VIP: AT LEAST 12 MONTHS OF HISTORY AND SPENDING MORE THEN €5000.
-- REGULAR: AT LEAST 12 MONTHS OF HISTORY BUT SPENDING €5000 OR LESS.
-- NEW: LIFESPAN LEDD THEN 12 MONTHS.
AND FIND THE TOTAL NUMBERS OF CUTOMERS BY EACH GROUPS */
WITH CUSTOMER_SPENDING AS(
SELECT 
	C.CUSTOMER_KEY,
    SUM(F.SALES_AMOUNT) AS TOTAL_SPENDING,
    MIN(ORDER_DATE) AS FIRST_ORDER,
    MAX(ORDER_DATE) AS LAST_ORDER,
    TIMESTAMPDIFF(MONTH, MIN(F.ORDER_DATE), MAX(F.ORDER_DATE)) AS LIFESPAN
FROM GOLD_FACT_SALES F 
LEFT JOIN GOLD_DIM_CUSTOMERS C ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY C.CUSTOMER_KEY)
SELECT CUSTOMER_SEGMENT, 
COUNT(CUSTOMER_KEY) AS TOTAL_CUSTOMER
FROM(
	SELECT 
		CUSTOMER_KEY,
			CASE
				WHEN LIFESPAN >=12 AND TOTAL_SPENDING > 5000 THEN 'VIP' 
				WHEN LIFESPAN > 12 AND TOTAL_SPENDING < 5000 THEN 'REGULAR'
				ELSE 'NEW'
			END CUSTOMER_SEGMENT
		FROM CUSTOMER_SPENDING) AS SEGMENT_CUSTOMERS GROUP BY CUSTOMER_SEGMENT
		ORDER BY TOTAL_CUSTOMER DESC;
 









