/*
===============================================================================
DATABASE EXPLORATION
===============================================================================
PURPOSE:
    - TO EXPLORE THE STRUCTURE OF THE DATABASE, INCLUDING THE LIST OF TABLES AND THEIR SCHEMAS.
    - TO INSPECT THE COLUMNS AND METADATA FOR SPECIFIC TABLES.

TABLES USED:
    - INFORMATION_SCHEMA.TABLES
    - INFORMATION_SCHEMA.COLUMNS
===============================================================================
*/

-- RETRIEVE A LIST OF ALL TABLES IN THE DATABASE
SELECT 
    TABLE_SCHEMA, 
    TABLE_NAME, 
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'GOLD';

-- RETRIEVE ALL COLUMNS FOR A SPECIFIC TABLE (DIM_CUSTOMERS)
SELECT 
    COLUMN_NAME, 
    DATA_TYPE, 
    IS_NULLABLE, 
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'GOLD'
  AND TABLE_NAME = 'DIM_CUSTOMERS';
