/*
===============================================================================
DATE RANGE EXPLORATION
===============================================================================
PURPOSE:
    - TO DETERMINE THE TEMPORAL BOUNDARIES OF KEY DATA POINTS.
    - TO UNDERSTAND THE RANGE OF HISTORICAL DATA.

SQL FUNCTIONS USED:
    - MIN(), MAX(), TIMESTAMPDIFF()
===============================================================================
*/

-- DETERMINE THE FIRST AND LAST ORDER DATE AND THE TOTAL DURATION IN MONTHS
SELECT 
    MIN(ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(ORDER_DATE) AS LAST_ORDER_DATE,
    TIMESTAMPDIFF(MONTH, MIN(ORDER_DATE), MAX(ORDER_DATE)) AS ORDER_RANGE_MONTHS
FROM GOLD_FACT_SALES;

-- FIND THE YOUNGEST AND OLDEST CUSTOMER BASED ON BIRTHDATE
SELECT
    MIN(BIRTHDATE) AS OLDEST_BIRTHDATE,
    TIMESTAMPDIFF(YEAR, MIN(BIRTHDATE), CURDATE()) AS OLDEST_AGE,
    MAX(BIRTHDATE) AS YOUNGEST_BIRTHDATE,
    TIMESTAMPDIFF(YEAR, MAX(BIRTHDATE), CURDATE()) AS YOUNGEST_AGE
FROM GOLD_DIM_CUSTOMERS;
