/*
===============================================================================
MEASURES EXPLORATION (KEY METRICS)
===============================================================================
PURPOSE:
    - TO CALCULATE AGGREGATED METRICS (E.G., TOTALS, AVERAGES) FOR QUICK INSIGHTS.
    - TO IDENTIFY OVERALL TRENDS OR SPOT ANOMALIES.

SQL FUNCTIONS USED:
    - COUNT(), SUM(), AVG()
===============================================================================
*/

-- FIND THE TOTAL SALES
SELECT SUM(SALES_AMOUNT) AS TOTAL_SALES 
FROM GOLD_FACT_SALES;

-- FIND HOW MANY ITEMS ARE SOLD
SELECT SUM(QUANTITY) AS TOTAL_QUANTITY 
FROM GOLD_FACT_SALES;

-- FIND THE AVERAGE SELLING PRICE
SELECT AVG(PRICE) AS AVG_PRICE 
FROM GOLD_FACT_SALES;

-- FIND THE TOTAL NUMBER OF ORDERS
SELECT COUNT(ORDER_NUMBER) AS TOTAL_ORDERS 
FROM GOLD_FACT_SALES;

-- FIND THE TOTAL NUMBER OF DISTINCT ORDERS
SELECT COUNT(DISTINCT ORDER_NUMBER) AS TOTAL_ORDERS 
FROM GOLD_FACT_SALES;

-- FIND THE TOTAL NUMBER OF PRODUCTS
SELECT COUNT(PRODUCT_NAME) AS TOTAL_PRODUCTS 
FROM GOLD_DIM_PRODUCTS;

-- FIND THE TOTAL NUMBER OF CUSTOMERS
SELECT COUNT(CUSTOMER_KEY) AS TOTAL_CUSTOMERS 
FROM GOLD_DIM_CUSTOMERS;

-- FIND THE TOTAL NUMBER OF CUSTOMERS THAT HAVE PLACED AN ORDER
SELECT COUNT(DISTINCT CUSTOMER_KEY) AS TOTAL_CUSTOMERS 
FROM GOLD_FACT_SALES;

-- GENERATE A REPORT THAT SHOWS ALL KEY METRICS OF THE BUSINESS
SELECT 'TOTAL SALES' AS MEASURE_NAME, SUM(SALES_AMOUNT) AS MEASURE_VALUE 
FROM GOLD_FACT_SALES
UNION ALL
SELECT 'TOTAL QUANTITY', SUM(QUANTITY) 
FROM GOLD_FACT_SALES
UNION ALL
SELECT 'AVERAGE PRICE', AVG(PRICE) 
FROM GOLD_FACT_SALES
UNION ALL
SELECT 'TOTAL ORDERS', COUNT(DISTINCT ORDER_NUMBER) 
FROM GOLD_FACT_SALES
UNION ALL
SELECT 'TOTAL PRODUCTS', COUNT(DISTINCT PRODUCT_NAME) 
FROM GOLD_DIM_PRODUCTS
UNION ALL
SELECT 'TOTAL CUSTOMERS', COUNT(CUSTOMER_KEY) 
FROM GOLD_DIM_CUSTOMERS;
