/*
===============================================================================
PART-TO-WHOLE ANALYSIS
===============================================================================
PURPOSE:
    - TO COMPARE PERFORMANCE OR METRICS ACROSS DIMENSIONS OR TIME PERIODS.
    - TO EVALUATE DIFFERENCES BETWEEN CATEGORIES.
    - USEFUL FOR A/B TESTING OR REGIONAL COMPARISONS.

SQL FUNCTIONS USED:
    - SUM(), AVG(): AGGREGATES VALUES FOR COMPARISON.
    - WINDOW FUNCTIONS: SUM() OVER() FOR TOTAL CALCULATIONS.
===============================================================================
*/

-- WHICH CATEGORIES CONTRIBUTE THE MOST TO OVERALL SALES.
WITH CATEGORY_SALES AS(
SELECT CATEGORY,
	SUM(F.SALES_AMOUNT) AS TOTAL_SALES 
    FROM GOLD_FACT_SALES F
    LEFT JOIN GOLD_DIM_PRODUCTS P ON P.PRODUCT_KEY = F.PRODUCT_KEY
    GROUP BY CATEGORY)
SELECT CATEGORY,
	TOTAL_SALES,
    SUM(TOTAL_SALES) OVER() AS OVERALL_SALES,
    CONCAT(ROUND((CAST(TOTAL_SALES AS FLOAT) / SUM(TOTAL_SALES) OVER()) * 100,2),'%') AS PERCENTAGE_OF_TOTAL
    FROM CATEGORY_SALES WHERE CATEGORY IS NOT NULL ORDER BY TOTAL_SALES DESC;
    
    
    
    
