/*
===============================================================================
PERFORMANCE ANALYSIS (YEAR-OVER-YEAR, MONTH-OVER-MONTH)
===============================================================================
PURPOSE:
    - TO MEASURE THE PERFORMANCE OF PRODUCTS, CUSTOMERS, OR REGIONS OVER TIME.
    - FOR BENCHMARKING AND IDENTIFYING HIGH-PERFORMING ENTITIES.
    - TO TRACK YEARLY TRENDS AND GROWTH.

SQL FUNCTIONS USED:
    - LAG(): ACCESSES DATA FROM PREVIOUS ROWS.
    - AVG() OVER(): COMPUTES AVERAGE VALUES WITHIN PARTITIONS.
    - CASE: DEFINES CONDITIONAL LOGIC FOR TREND ANALYSIS.
===============================================================================
*/

/* ANALYZE THE YEARLY PERFORMANCE OF PRODUCTS BY COMPARING THEIR SALES TO BOTH THE AVGERAGE
SALES PERFORMANCE OF THE PRODUCT AND THE PREVIOUS YEAR'S SALES.*/

WITH YEARLY_PRODUCT_SALES AS (
	SELECT 
    YEAR(F.ORDER_DATE) AS ORDER_YEAR,
    P.PRODUCT_NAME,
    SUM(F.SALES_AMOUNT) AS CURRENT_SALES 
    FROM GOLD_FACT_SALES F LEFT JOIN GOLD_DIM_PRODUCTS P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY WHERE F.ORDER_DATE IS NOT NULL
    GROUP BY YEAR(F.ORDER_DATE),P.PRODUCT_NAME)
    SELECT 
    ORDER_YEAR,PRODUCT_NAME,CURRENT_SALES,
    AVG(CURRENT_SALES) OVER(PARTITION BY PRODUCT_NAME) AS AVG_SALES,
    CURRENT_SALES - AVG(CURRENT_SALES) OVER(PARTITION BY PRODUCT_NAME) AS DIFF_AVG,
CASE
	  WHEN CURRENT_SALES - AVG(CURRENT_SALES) OVER(PARTITION BY PRODUCT_NAME) > 0 THEN 'ABOVE AVG'
    WHEN CURRENT_SALES - AVG(CURRENT_SALES) OVER(PARTITION BY PRODUCT_NAME) < 0 THEN 'BELOW AVG'
    ELSE 'AVG'
    END AVG_CHANGE,
    LAG(CURRENT_SALES) OVER(PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) AS PY_SALES,
    CURRENT_SALES - LAG(CURRENT_SALES) OVER(PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) AS DIFF_PY,
CASE
		WHEN CURRENT_SALES - LAG(CURRENT_SALES) OVER(PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) > 0 THEN 'INCREASE'
    WHEN CURRENT_SALES - LAG(CURRENT_SALES) OVER(PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) < 0 THEN 'DECREASE'
    ELSE 'NO CHANGE'
    END AS PY_CHANGE
FROM YEARLY_PRODUCT_SALES ORDER BY PRODUCT_NAME,ORDER_YEAR;



