/*
===============================================================================
RANKING ANALYSIS
===============================================================================
PURPOSE:
    - TO RANK ITEMS (E.G., PRODUCTS, CUSTOMERS) BASED ON PERFORMANCE OR OTHER METRICS.
    - TO IDENTIFY TOP PERFORMERS OR LAGGARDS.

SQL FUNCTIONS USED:
    - WINDOW RANKING FUNCTIONS: RANK(), DENSE_RANK(), ROW_NUMBER()
    - CLAUSES: GROUP BY, ORDER BY, LIMIT
===============================================================================
*/

-- WHICH 5 PRODUCTS GENERATE THE HIGHEST REVENUE? (SIMPLE RANKING)
SELECT
    P.PRODUCT_NAME,
    SUM(F.SALES_AMOUNT) AS TOTAL_REVENUE
FROM GOLD_FACT_SALES F
LEFT JOIN GOLD_DIM_PRODUCTS P
    ON P.PRODUCT_KEY = F.PRODUCT_KEY
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

-- COMPLEX BUT FLEXIBLE RANKING USING WINDOW FUNCTIONS
SELECT *
FROM (
    SELECT
        P.PRODUCT_NAME,
        SUM(F.SALES_AMOUNT) AS TOTAL_REVENUE,
        RANK() OVER (ORDER BY SUM(F.SALES_AMOUNT) DESC) AS RANK_PRODUCTS
    FROM GOLD_FACT_SALES F
    LEFT JOIN GOLD_DIM_PRODUCTS P
        ON P.PRODUCT_KEY = F.PRODUCT_KEY
    GROUP BY P.PRODUCT_NAME
) AS RANKED_PRODUCTS
WHERE RANK_PRODUCTS <= 5;

-- 5 WORST-PERFORMING PRODUCTS IN TERMS OF SALES
SELECT
    P.PRODUCT_NAME,
    SUM(F.SALES_AMOUNT) AS TOTAL_REVENUE
FROM GOLD_FACT_SALES F
LEFT JOIN GOLD_DIM_PRODUCTS P
    ON P.PRODUCT_KEY = F.PRODUCT_KEY
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE ASC
LIMIT 5;

-- TOP 10 CUSTOMERS WHO HAVE GENERATED THE HIGHEST REVENUE
SELECT
    C.CUSTOMER_KEY,
    C.FIRST_NAME,
    C.LAST_NAME,
    SUM(F.SALES_AMOUNT) AS TOTAL_REVENUE
FROM GOLD_FACT_SALES F
LEFT JOIN GOLD_DIM_CUSTOMERS C
    ON C.CUSTOMER_KEY = F.CUSTOMER_KEY
GROUP BY 
    C.CUSTOMER_KEY,
    C.FIRST_NAME,
    C.LAST_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- 3 CUSTOMERS WITH THE FEWEST ORDERS PLACED
SELECT
    C.CUSTOMER_KEY,
    C.FIRST_NAME,
    C.LAST_NAME,
    COUNT(DISTINCT F.ORDER_NUMBER) AS TOTAL_ORDERS
FROM GOLD_FACT_SALES F
LEFT JOIN GOLD_DIM_CUSTOMERS C
    ON C.CUSTOMER_KEY = F.CUSTOMER_KEY
GROUP BY 
    C.CUSTOMER_KEY,
    C.FIRST_NAME,
    C.LAST_NAME
ORDER BY TOTAL_ORDERS ASC
LIMIT 3;
