/*
===============================================================================
PRODUCT REPORT
===============================================================================
PURPOSE:
    - THIS REPORT CONSOLIDATES KEY PRODUCT METRICS AND BEHAVIORS.

HIGHLIGHTS:
    1. GATHERS ESSENTIAL FIELDS SUCH AS PRODUCT NAME, CATEGORY, SUBCATEGORY, AND COST.
    2. SEGMENTS PRODUCTS BY REVENUE TO IDENTIFY HIGH-PERFORMERS, MID-RANGE, OR LOW-PERFORMERS.
    3. AGGREGATES PRODUCT-LEVEL METRICS:
       - TOTAL ORDERS
       - TOTAL SALES
       - TOTAL QUANTITY SOLD
       - TOTAL CUSTOMERS (UNIQUE)
       - LIFESPAN (IN MONTHS)
    4. CALCULATES VALUABLE KPIS:
       - RECENCY (MONTHS SINCE LAST SALE)
       - AVERAGE ORDER REVENUE (AOR)
       - AVERAGE MONTHLY REVENUE
===============================================================================
*/
/*
===============================================================================
CREATE REPORT: GOLD.REPORT_PRODUCTS
===============================================================================
*/
/*---------------------------------------------------------------------------
1) BASE QUERY: RETRIEVES CORE COLUMNS FROM FACT_SALES AND DIM_PRODUCTS
---------------------------------------------------------------------------*/
DROP VIEW IF EXISTS GOLD_REPORT_PRODUCTS;
CREATE VIEW GOLD_REPORT_PRODUCTS AS
WITH BASE_QUERY AS(SELECT
        F.ORDER_NUMBER,
        F.ORDER_DATE,
        F.CUSTOMER_KEY,
        F.SALES_AMOUNT,
        F.QUANTITY,
        P.PRODUCT_KEY,
        P.PRODUCT_NAME,
        P.CATEGORY,
        P.SUBCATEGORY,
        P.COST
    FROM GOLD_FACT_SALES F
    LEFT JOIN GOLD_DIM_PRODUCTS P
        ON F.PRODUCT_KEY = P.PRODUCT_KEY
    WHERE F.ORDER_DATE IS NOT NULL
),		-- PRODUCT AGGREGATIONS: SUMMARIZES KEY METRICS AT THE PRODUCT LEVEL 
PRODUCT_AGGREGATIONS AS(SELECT
        PRODUCT_KEY,
        PRODUCT_NAME,
        CATEGORY,
        SUBCATEGORY,
        COST,
        TIMESTAMPDIFF(MONTH, MIN(ORDER_DATE), MAX(ORDER_DATE)) AS LIFESPAN,
        MAX(ORDER_DATE) AS LAST_SALE_DATE,
        COUNT(DISTINCT ORDER_NUMBER) AS TOTAL_ORDERS,
        COUNT(DISTINCT CUSTOMER_KEY) AS TOTAL_CUSTOMERS,
        SUM(SALES_AMOUNT) AS TOTAL_SALES,
        SUM(QUANTITY) AS TOTAL_QUANTITY,
        ROUND(AVG(SALES_AMOUNT / NULLIF(QUANTITY, 0)), 1) AS AVG_SELLING_PRICE
    FROM BASE_QUERY
    GROUP BY PRODUCT_KEY, PRODUCT_NAME, CATEGORY, SUBCATEGORY, COST
)		-- FINAL QUERY: COMBINES ALL PRODUCT RESULTS INTO ONE OUTPUT
SELECT
    PRODUCT_KEY,
    PRODUCT_NAME,
    CATEGORY,
    SUBCATEGORY,
    COST,
    LAST_SALE_DATE,
    TIMESTAMPDIFF(MONTH, LAST_SALE_DATE, CURDATE()) AS RECENCY_IN_MONTHS,
    CASE
        WHEN TOTAL_SALES > 50000 THEN 'HIGH-PERFORMER'
        WHEN TOTAL_SALES >= 10000 THEN 'MID-RANGE'
        ELSE 'LOW-PERFORMER'
    END AS PRODUCT_SEGMENT,
    LIFESPAN,
    TOTAL_ORDERS,
    TOTAL_SALES,
    TOTAL_QUANTITY,
    TOTAL_CUSTOMERS,
    AVG_SELLING_PRICE,
    CASE 
        WHEN TOTAL_ORDERS = 0 THEN 0
        ELSE TOTAL_SALES / TOTAL_ORDERS
    END AS AVG_ORDER_REVENUE,
    CASE
        WHEN LIFESPAN = 0 THEN TOTAL_SALES
        ELSE TOTAL_SALES / LIFESPAN
    END AS AVG_MONTHLY_REVENUE
FROM PRODUCT_AGGREGATIONS;

SELECT * FROM GOLD_REPORT_PRODUCTS;




















