/*
===============================================================================
CUSTOMER REPORT
===============================================================================
PURPOSE:
    - THIS REPORT CONSOLIDATES KEY CUSTOMER METRICS AND BEHAVIORS

HIGHLIGHTS:
    1. GATHERS ESSENTIAL FIELDS SUCH AS NAMES, AGES, AND TRANSACTION DETAILS.
    2. SEGMENTS CUSTOMERS INTO CATEGORIES (VIP, REGULAR, NEW) AND AGE GROUPS.
    3. AGGREGATES CUSTOMER-LEVEL METRICS:
       - TOTAL ORDERS
       - TOTAL SALES
       - TOTAL QUANTITY PURCHASED
       - TOTAL PRODUCTS
       - LIFESPAN (IN MONTHS)
    4. CALCULATES VALUABLE KPIS:
       - RECENCY (MONTHS SINCE LAST ORDER)
       - AVERAGE ORDER VALUE
       - AVERAGE MONTHLY SPEND
===============================================================================
*/
/*---------------------------------------------------------------------------
1) Base Query: Retrieves core columns from tables
---------------------------------------------------------------------------*/
CREATE VIEW GOLD_REPORT_CUSTOMERS AS
WITH BASE_QUERY AS(
SELECT 
	F.ORDER_NUMBER,
    F.PRODUCT_KEY,
    F.ORDER_DATE,
    F.SALES_AMOUNT,
    F.QUANTITY,
    C.CUSTOMER_KEY,
    C.CUSTOMER_NUMBER,
    CONCAT(C.FIRST_NAME,' ',C.LAST_NAME) AS CUSTOMER_NAME,
    TIMESTAMPDIFF(YEAR, C.BIRTHDATE, CURDATE()) AS AGE
FROM GOLD_FACT_SALES F LEFT JOIN
GOLD_DIM_CUSTOMERS C ON C.CUSTOMER_KEY = F.CUSTOMER_KEY
WHERE ORDER_DATE IS NOT NULL),
CUSTOMER_AGGREGATION AS(           -- CUSTOMER AGGREGATIONS: SUMMARIZES KEY METRICS AT THE CUSTOMER LEVEL
SELECT 
	CUSTOMER_KEY,
    CUSTOMER_NUMBER,
    CUSTOMER_NAME,
    AGE,
    COUNT(DISTINCT ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(SALES_AMOUNT) AS TOTAL_SALES,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    COUNT(DISTINCT PRODUCT_KEY) AS TOTAL_PRODUCTS,
    MAX(ORDER_DATE) AS LAST_ORDER_DATE,
    TIMESTAMPDIFF(MONTH, MIN(ORDER_DATE),MAX(ORDER_DATE)) AS LIFESPAN
FROM BASE_QUERY
GROUP BY CUSTOMER_KEY,
		CUSTOMER_NUMBER,
		CUSTOMER_NAME,
		AGE)
SELECT
	CUSTOMER_KEY,
    CUSTOMER_NUMBER,
    CUSTOMER_NAME,
    AGE,
    CASE
		WHEN AGE < 20 THEN 'UNDER 20'
        WHEN AGE BETWEEN 20 AND 29 THEN '20 - 29'
        WHEN AGE BETWEEN 30 AND 39 THEN '30 - 39'
        WHEN AGE BETWEEN 40 AND 49 THEN '40 - 49'
        ELSE '50 AND ABOVE'
	END AS AGE_GROUP,
	CASE
		WHEN LIFESPAN >= 12 AND TOTAL_SALES > 5000 THEN 'VIP'
        WHEN LIFESPAN >= 12 AND TOTAL_SALES <= 5000 THEN 'REGULAR'
        ELSE 'NEW'
	END AS CUSTOMER_SEGMENT,
    LAST_ORDER_DATE,
    TIMESTAMPDIFF(MONTH, LAST_ORDER_DATE, CURDATE()) AS RECENCY_MONTHS,
    TOTAL_ORDERS,
    TOTAL_SALES,
    TOTAL_QUANTITY,
    TOTAL_PRODUCTS,
    LIFESPAN,
    -- COMPUATE AVERAGE ORDER VALUE (AVO)
    CASE
		WHEN TOTAL_SALES = 0 THEN 0
        ELSE TOTAL_SALES / TOTAL_ORDERS
        END AS AVG_ORDER_VALUE,
	-- COMPUATE AVERAGE MONTHLY SPEND
    CASE
		WHEN LIFESPAN = 0 THEN TOTAL_SALES
        ELSE TOTAL_SALES / LIFESPAN
        END AS AVG_MONTHLY_SPEND
    FROM CUSTOMER_AGGREGATION;

SELECT * FROM GOLD_REPORT_CUSTOMERS;









